global:
  scrape_interval:      15s
  evaluation_interval:  15s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'phpmyadmin'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'mysql'
    static_configs:
      - targets: ['10.244.0.102:3306'] 
