name: Build and deploy Docker images

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: sens31/ehospital

jobs:
          
  ip:
    runs-on: ubuntu-latest
    steps:
      - name: Get runner IP address
        run: |
          ip=$(curl -s https://api.ipify.org)
          for i in {1..10}; do
            echo "The IP address of the runner is: $ip"
          done      
          
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        env:
          DOCKER_BUILDKIT: 1
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          
  compose:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        run: git clone https://github.com/sensgithub/eHospital.git
        working-directory: ${{ github.workspace }}
      
      - name: Start services
        run: |
          cd eHospital
          docker-compose up -d

# Prometheus
  prometheus:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Start Prometheus
        run: |
          docker run -d --name prometheus -p 9090:9090 prom/prometheus

# Grafana 
  grafana:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Start Grafana
        run: |
          docker run -d --name grafana -p 3000:3000 grafana/grafana
