version: '3.9'
services:

  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=ehospital
      - MYSQL_USER=ehospital
      - MYSQL_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # persistent db 
      
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html" 
    ports:
      - 80:80
      - 443:443 # for future ssl traffic

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
